### ISSUE TITLE
[Bug]: OutlookGridView throws a MissingManifestResourceException when trying to configure its columns

### ISSUE THREAD

**Issue by Ahmed-Abdelhameed** [Krypton-Suite/Extended-Toolkit#226]
**Describe the bug**
I've been using an old version of `OutlookGridView` and just tried to upgrade to the [latest NuGet package](https://www.nuget.org/packages/Krypton.Toolkit.Suite.Extended.Outlook.Grid/5.550.2106). When I ran the application, it threw a `MissingManifestResourceException`.

**To Reproduce**
1. Add an `OutlookGridView` control to the form and add a couple of columns to it.
2. In the form's constructor add the following code:
```
foreach (DataGridViewColumn col in kryptonOutlookGrid1.Columns)
{
    col.SortMode = DataGridViewColumnSortMode.Programmatic;
    kryptonOutlookGrid1.AddInternalColumn(
        col, new OutlookGridDefaultGroup(null), SortOrder.None, -1, -1);
}
```
3. Run the program.
4. See error.

Here's the full stack trace:

```
System.Resources.MissingManifestResourceException
  HResult=0x80131532
  Message=Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "Krypton.Toolkit.Suite.Extended.Outlook.Grid.Utilities.Language.Strings.resources" was correctly embedded or linked into assembly "Krypton.Toolkit.Suite.Extended.Outlook.Grid" at compile time, or that all the satellite assemblies required are loadable and fully signed.
  Source=mscorlib
  StackTrace:
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at Krypton.Toolkit.Suite.Extended.Outlook.Grid.LanguageManager.GetLocalisedString(String name)
   at Krypton.Toolkit.Suite.Extended.Outlook.Grid.OutlookGridDefaultGroup..ctor()
   at Krypton.Toolkit.Suite.Extended.Outlook.Grid.OutlookGridDefaultGroup..ctor(IOutlookGridGroup parentGroup)
   at TmpOutlookGridNewTest.Form1..ctor() in \TmpOutlookGridNewTest\TmpOutlookGridNewTest\Form1.cs:line 23
   at TmpOutlookGridNewTest.Program.Main() in \TmpOutlookGridNewTest\TmpOutlookGridNewTest\Program.cs:line 19
```

**Environment:**
 - OS: Windows 10 build 19043.
 - .NET Framework 4.7.2.
 - OutlookGrid module version: 5.550.2106.

**Comment by Wagnerp** [comment]
Possible link to #268

**Comment by Wagnerp** [comment]
Fixed - 19/01/2022
